"""relation fix

Revision ID: 685a59c9fbd5
Revises: e715c0b5b2d4
Create Date: 2021-09-21 07:59:08.091876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '685a59c9fbd5'
down_revision = 'e715c0b5b2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('sender_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'notification', 'notification_senders', ['sender_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_column('notification', 'sender_id')
    # ### end Alembic commands ###
