"""initial

Revision ID: e715c0b5b2d4
Revises: 
Create Date: 2021-09-20 17:40:46.023650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e715c0b5b2d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('notification_type', postgresql.ENUM('Error', 'Info', 'Success', 'Warning', name='notification_types'), nullable=True),
    sa.Column('action', postgresql.ENUM('New', 'Deleted', 'Viewed', 'Archived', name='notification_actions'), nullable=True),
    sa.Column('status', postgresql.ENUM('New', 'Deleted', 'Viewed', 'Archived', name='notification_statuses'), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_senders',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_senders')
    op.drop_table('notification')
    # ### end Alembic commands ###
